name: Build SCSS

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install node
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install -g sass

    - name: Compile colors
      run: sass styles/colors.scss:./dist/colors.css

    - name: Compile layout
      run: sass styles/layout.scss:./dist/layout.css

    - name: Compile theme
      run: sass theme.scss:./dist/theme.css

    - name: Copy fonts
      run: |
        cp ./fonts/*.css ./dist/font

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
