name: Build SCSS

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install node
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install -g sass

    - name: Compile colors-static.css
      run: sass --no-source-map --style=compressed styles/colors-static.scss:./dist/colors-static.css

    - name: Compile colors-dynamic.css
      run: sass --no-source-map --style=compressed styles/colors-dynamic.scss:./dist/colors-dynamic.css

    - name: Compile layout.css
      run: sass --no-source-map --style=compressed styles/layout.scss:./dist/layout.css

    - name: Compile theme.css
      run: sass --no-source-map --style=compressed theme.scss:./dist/theme.css

    - name: Compile theme.user.css
      run: sass --no-source-map theme.user.scss:./dist/theme.user.css

    - name: Create font directory
      run: mkdir -p ./dist/fonts

    - name: Copy fonts
      run: |
        cp ./fonts/*.css ./dist/fonts

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
